### ISSUE TITLE
Outline includes text in comments.

### ISSUE THREAD

**Issue by DeeHants** [hitode909/vscode-perl-outline#1]
Issue Type: <b>Bug</b>

Have a perl file with this as a comment:
`# Call as a package method to avoid the overhead of loading offers if there is no linked offer.`
A "method" package appears in the outline list.

Extension version: 0.0.1
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:11.471Z)
OS version: Windows_NT ia32 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.75GB free)|
|Process Argv|C:\Program Files (x86)\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by hitode909** [comment]
@DeeHants Thank you for reporting!
I fixed it with [very heuristic change](https://github.com/hitode909/vscode-perl-outline/commit/c27348f4ab8a493ee5ccabe96aef827c6bab6183), and released version 0.0.3.

**Comment by DeeHants** [comment]
ohh, bug number 1!
Thanks for the fix, and I'll try and convince VSCode to give me the update!
