### ISSUE TITLE
Follow Cursor

### ISSUE THREAD

**Issue by danstewart** [hitode909/vscode-perl-outline#11]
Is it possible to make this extension work with "Follow Cursor" enabled?

**Comment by hitode909** [comment]
I think it is not possible.
This extension provides list of tokens and its positions for VSCode. Displaying outline information is VSCode's job.
- https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider

Do you know some extensions which supports Follow Cursor? If you know, please let me know. I'll check that code and may be I can implement it.
Thank you.

**Comment by danstewart** [comment]
The ruby [solargraph extension](https://github.com/castwide/vscode-solargraph) does but I think that might come from Solargraph rather than the extension.

Thanks anyway

**Comment by hitode909** [comment]
Thank you for information, I'll check the solagraph extension later!
