### ISSUE TITLE
Please add your chosen license

### ISSUE THREAD

**Issue by tomaszjasiak** [hitode909/vscode-perl-outline#2]
Hi,

Could you add an open source license or another which you deem appropriate to your plugin?
The VSCode perl-outline plugin seems very interesting but using it without an explicit license is not allowed for me and most likely for many others as well.

Thanks for creating it since it seems to be a very interesting and useful addition to VS Code.

Thanks,
Tomasz Jasiak

**Comment by hitode909** [comment]
@tomaszjasiak Thank you for your feedback, I was just forgot to add the license file.
I committed the license file just now: https://github.com/hitode909/vscode-perl-outline/commit/12c7224252ac8d783f7e048f56fe17622c5fd030
